# Sample local configuration file 
# Copy this to application-local.yml and replace with your actual Infura project ID
# application-local.yml is gitignored to protect your private keys

ethereum:
  # HTTP connection for general Web3 calls
  node-url: https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID
  
  # WebSocket connection for streaming block events (NEW FEATURE)
  websocket-url: wss://mainnet.infura.io/ws/v3/YOUR_INFURA_PROJECT_ID
  
  # Start from latest block
  start-block: null
  
  # Block polling interval (not used for WebSocket connections)
  block-polling-interval: 1000
  
  # Example contract configurations
  contracts:
    # USDC Token Contract - Monitor for large transfers
    - name: "USDC"
      address: "0xA0b86a33E6441c8c6c0D4B7D5E7b4F5B7E7E7E7E"
      events:
        - name: "Transfer"
          signature: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
          topics: []
          enabled: true

logging:
  level:
    dev.ps.ethblockevents: INFO
    org.web3j: WARN
    root: INFO