ethereum:
  # Infura node URL (replace with your Infura project ID)
  node-url: https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID
  
  # Infura WebSocket URL (replace with your Infura project ID)
  websocket-url: wss://mainnet.infura.io/ws/v3/YOUR_INFURA_PROJECT_ID
  
  # Starting block number (null means start from latest)
  start-block: null
  
  # Block polling interval in milliseconds
  block-polling-interval: 1000
  
  # Contract configurations
  contracts:
    # Example ERC20 token contract (USDC)
    - name: "USDC"
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      events:
        - name: "Transfer"
          signature: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
          topics: []
          enabled: false
    
    # Example custom contract
    - name: "CustomContract"
      address: "0x1234567890123456789012345678901234567890"
      events:
        - name: "CustomEvent"
          signature: "0x1234567890abcdef..."
          topics: []
          enabled: false

logging:
  level:
    dev.ps.ethblockevents: INFO
    org.web3j: WARN
    io.reactivex: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring Boot configuration
spring:
  application:
    name: eth-block-events
  main:
    banner-mode: console
  profiles:
    active: local